from django.db import models

# Create your models here.

class Boyd3(models.Model):
    def __str__(self):
        return self.age
    age = models.CharField(max_length=20)
    sex = models.CharField(max_length=20)
    low_age = models.DecimalField(max_digits=10, decimal_places=2)
    high_age = models.DecimalField(max_digits=10, decimal_places=2)
    testes_no = models.IntegerField(default=0)
    testes_wgt = models.DecimalField(max_digits=10, decimal_places=2)
    t_e_no = models.IntegerField(default=0)
    t_e_wgt = models.DecimalField(max_digits=10, decimal_places=2)
    sem_ves_no = models.IntegerField(default=0)
    sem_ves_wgt = models.DecimalField(max_digits=10, decimal_places=2)
    pgl_no = models.IntegerField(default=0)
    pgl_wgt = models.DecimalField(max_digits=10, decimal_places=2)
    
    
class Boyd4(models.Model):
    def __str__(self):
        return self.age
    age = models.CharField(max_length=20)
    sex = models.CharField(max_length=20)
    low_age = models.DecimalField(max_digits=10, decimal_places=2)
    high_age = models.DecimalField(max_digits=10, decimal_places=2)
    ovary_no = models.IntegerField(default=0)
    ovary_wgt = models.DecimalField(max_digits=10, decimal_places=2)
    f_tube_no = models.IntegerField(default=0)
    f_tube_wgt = models.DecimalField(max_digits=10, decimal_places=2)
    uterus_no = models.IntegerField(default=0)
    uterus_wgt = models.DecimalField(max_digits=10, decimal_places=2)
    
class Boyd56(models.Model):
    age = models.CharField(max_length=20)
    sex = models.CharField(max_length=20)
    low_age = models.DecimalField(max_digits=10, decimal_places=2)
    high_age = models.DecimalField(max_digits=10, decimal_places=2)
    adr_no = models.IntegerField(default=0)
    adr_wgt = models.DecimalField(max_digits=10, decimal_places=2)
    hypo_no = models.IntegerField(default=0)
    hypo_wgt = models.DecimalField(max_digits=10, decimal_places=2)
    panc_no = models.IntegerField(default=0)
    panc_wgt = models.DecimalField(max_digits=10, decimal_places=2)
    thyroid_no = models.IntegerField(default=0)
    thyroid_wgt = models.DecimalField(max_digits=10, decimal_places=2)

class BoydIII(models.Model):
    age = models.CharField(max_length=20)
    sex = models.CharField(max_length=20)
    low_age = models.DecimalField(max_digits=10, decimal_places=2)
    high_age = models.DecimalField(max_digits=10, decimal_places=2)
    brain_no = models.IntegerField(default=0)
    brain_wgt = models.DecimalField(max_digits=10, decimal_places=2)
    lung_no = models.IntegerField(default=0)
    lung_wgt = models.DecimalField(max_digits=10, decimal_places=2)
    heart_no = models.IntegerField(default=0)
    heart_wgt = models.DecimalField(max_digits=10, decimal_places=2)
    kidneys_no = models.IntegerField(default=0)
    kidneys_wgt = models.DecimalField(max_digits=10, decimal_places=2)
    liver_no = models.IntegerField(default=0)
    liver_wgt = models.DecimalField(max_digits=10, decimal_places=2)
    spleen_no = models.IntegerField(default=0)
    spleen_wgt = models.DecimalField(max_digits=10, decimal_places=2)

class Days(models.Model):
    y_days = models.DecimalField(max_digits=13, decimal_places=11)
    sex = models.CharField(max_length=20)
    low_day = models.IntegerField(default=0)
    high_day = models.IntegerField(default=0)
    
class k_brain(models.Model):
    y_days = models.DecimalField(max_digits=13, decimal_places=11)
    sex = models.CharField(max_length=20)
    n = models.IntegerField(default=0)
    high_day = models.IntegerField(default=0)
    low_val =  models.DecimalField(max_digits=10, decimal_places=2)
    mean_val =  models.DecimalField(max_digits=10, decimal_places=2)
    high_val =  models.DecimalField(max_digits=10, decimal_places=2)    
    
class k_heart(models.Model):
    y_days = models.DecimalField(max_digits=13, decimal_places=11)
    sex = models.CharField(max_length=20)
    n = models.IntegerField(default=0)
    high_day = models.IntegerField(default=0)
    low_val =  models.DecimalField(max_digits=10, decimal_places=2)
    mean_val =  models.DecimalField(max_digits=10, decimal_places=2)
    high_val =  models.DecimalField(max_digits=10, decimal_places=2)

class l_kidney(models.Model):
    y_days = models.DecimalField(max_digits=13, decimal_places=11)
    sex = models.CharField(max_length=20)
    n = models.IntegerField(default=0)
    high_day = models.IntegerField(default=0)
    low_val =  models.DecimalField(max_digits=10, decimal_places=2)
    mean_val =  models.DecimalField(max_digits=10, decimal_places=2)
    high_val =  models.DecimalField(max_digits=10, decimal_places=2)
    
class l_lung(models.Model):
    y_days = models.DecimalField(max_digits=13, decimal_places=11)
    sex = models.CharField(max_length=20)
    n = models.IntegerField(default=0)
    high_day = models.IntegerField(default=0)
    low_val =  models.DecimalField(max_digits=10, decimal_places=2)
    mean_val =  models.DecimalField(max_digits=10, decimal_places=2)
    high_val =  models.DecimalField(max_digits=10, decimal_places=2)
    
class liver(models.Model):
    y_days = models.DecimalField(max_digits=13, decimal_places=11)
    sex = models.CharField(max_length=20)
    n = models.IntegerField(default=0)
    high_day = models.IntegerField(default=0)
    low_val =  models.DecimalField(max_digits=10, decimal_places=2)
    mean_val =  models.DecimalField(max_digits=10, decimal_places=2)
    high_val =  models.DecimalField(max_digits=10, decimal_places=2)

class r_kidney(models.Model):
    y_days = models.DecimalField(max_digits=13, decimal_places=11)
    sex = models.CharField(max_length=20)
    n = models.IntegerField(default=0)
    high_day = models.IntegerField(default=0)
    low_val =  models.DecimalField(max_digits=10, decimal_places=2)
    mean_val =  models.DecimalField(max_digits=10, decimal_places=2)
    high_val =  models.DecimalField(max_digits=10, decimal_places=2)
    
class r_lung(models.Model):
    y_days = models.DecimalField(max_digits=13, decimal_places=11)
    sex = models.CharField(max_length=20)
    n = models.IntegerField(default=0)
    high_day = models.IntegerField(default=0)
    low_val =  models.DecimalField(max_digits=10, decimal_places=2)
    mean_val =  models.DecimalField(max_digits=10, decimal_places=2)
    high_val =  models.DecimalField(max_digits=10, decimal_places=2)
    
class scho_hrt_bh(models.Model):
    hgt_cm = models.IntegerField(default=0)
    sex = models.CharField(max_length=20)
    h_hgt = models.IntegerField(default=0)
    hgt_in = models.IntegerField(default=0)
    l95 = models.IntegerField(default=0)
    P = models.IntegerField(default=0)
    u95 = models.IntegerField(default=0)
    
class scho_hrt_bw(models.Model):
    hgt_cm = models.IntegerField(default=0)
    sex = models.CharField(max_length=20)
    h_hgt = models.IntegerField(default=0)
    hgt_in = models.IntegerField(default=0)
    l95 = models.IntegerField(default=0)
    P = models.IntegerField(default=0)
    u95 = models.IntegerField(default=0)   
    
class scho_vent_val(models.Model):
    age = models.IntegerField(default=0)
    sex = models.CharField(max_length=20)
    h_age = models.IntegerField(default=0)
    rvl95 = models.DecimalField(max_digits=10, decimal_places=2)
    rvp = models.DecimalField(max_digits=10, decimal_places=2)
    rvu95 = models.DecimalField(max_digits=10, decimal_places=2)
    lvl95 = models.DecimalField(max_digits=10, decimal_places=2)
    lvp = models.DecimalField(max_digits=10, decimal_places=2)
    lvu95 = models.DecimalField(max_digits=10, decimal_places=2)
    sepl95 = models.DecimalField(max_digits=10, decimal_places=2)
    sepp = models.DecimalField(max_digits=10, decimal_places=2)
    sepu95 = models.DecimalField(max_digits=10, decimal_places=2)
    avl95 = models.DecimalField(max_digits=10, decimal_places=2)
    avlp = models.DecimalField(max_digits=10, decimal_places=2)
    avlu95 = models.DecimalField(max_digits=10, decimal_places=2)
    mvl95 = models.DecimalField(max_digits=10, decimal_places=2)
    mvp = models.DecimalField(max_digits=10, decimal_places=2)
    mvu95 = models.DecimalField(max_digits=10, decimal_places=2)
    pull95 = models.DecimalField(max_digits=10, decimal_places=2)
    pulp = models.DecimalField(max_digits=10, decimal_places=2)
    pulu95 = models.DecimalField(max_digits=10, decimal_places=2)
    trl95 = models.DecimalField(max_digits=10, decimal_places=2)
    trp = models.DecimalField(max_digits=10, decimal_places=2)
    tru95 = models.DecimalField(max_digits=10, decimal_places=2)
    
class schultz_heart(models.Model):
    age_year = models.DecimalField(max_digits=13, decimal_places=11)
    sex = models.CharField(max_length=20)
    age = models.CharField(max_length=20)
    l_age = models.DecimalField(max_digits=13, decimal_places=11)
    h_age = models.DecimalField(max_digits=13, decimal_places=11)
    g_age = models.IntegerField()
    b_wgt = models.IntegerField()
    lgt = models.DecimalField(max_digits=7, decimal_places=1)
    hrt_wgt = models.DecimalField(max_digits=7, decimal_places=1)
    lvt = models.DecimalField(max_digits=7, decimal_places=2)
    rvt = models.DecimalField(max_digits=7, decimal_places=2)
    tri = models.DecimalField(max_digits=7, decimal_places=1)
    pul = models.DecimalField(max_digits=7, decimal_places=1)
    mit = models.DecimalField(max_digits=7, decimal_places=1)
    aor = models.DecimalField(max_digits=7, decimal_places=1)
    
class spleen(models.Model):
    y_days = models.DecimalField(max_digits=13, decimal_places=11)
    sex = models.CharField(max_length=20)
    n = models.IntegerField(default=0)
    high_day = models.IntegerField(default=0)
    low_val =  models.DecimalField(max_digits=10, decimal_places=2)
    mean_val =  models.DecimalField(max_digits=10, decimal_places=2)
    high_val =  models.DecimalField(max_digits=10, decimal_places=2)
    
class ss_linbw(models.Model):
    body_weight = models.CharField(max_length=20)
    l_weight = models.IntegerField()
    h_weight = models.IntegerField()
    gestational_age = models.IntegerField()
    crown_rump = models.DecimalField(max_digits=7, decimal_places=1)
    crown_heel = models.DecimalField(max_digits=7, decimal_places=1)
    toe_heel = models.DecimalField(max_digits=7, decimal_places=1)
    brain = models.DecimalField(max_digits=7, decimal_places=1)
    thymus = models.DecimalField(max_digits=7, decimal_places=1)
    heart = models.DecimalField(max_digits=7, decimal_places=1)
    lungs_combined = models.DecimalField(max_digits=7, decimal_places=1)
    spleen = models.DecimalField(max_digits=7, decimal_places=1)
    liver = models.DecimalField(max_digits=7, decimal_places=1)
    kidneys_combined = models.DecimalField(max_digits=7, decimal_places=1)
    adrenals_combined = models.DecimalField(max_digits=7, decimal_places=1)
    pancreas = models.DecimalField(max_digits=7, decimal_places=1)
    
class ss_linbwrg(models.Model):
    body_weight = models.CharField(max_length=20)
    l_weight = models.IntegerField()
    h_weight = models.IntegerField()
    gestational_age = models.IntegerField()
    crown_rump = models.DecimalField(max_digits=7, decimal_places=1)
    crown_heel = models.DecimalField(max_digits=7, decimal_places=1)
    toe_heel = models.DecimalField(max_digits=7, decimal_places=1)
    brain = models.DecimalField(max_digits=7, decimal_places=1)
    thymus = models.DecimalField(max_digits=7, decimal_places=1)
    heart = models.DecimalField(max_digits=7, decimal_places=1)
    lungs_combined = models.DecimalField(max_digits=7, decimal_places=1)
    spleen = models.DecimalField(max_digits=7, decimal_places=1)
    liver = models.DecimalField(max_digits=7, decimal_places=1)
    kidneys_combined = models.DecimalField(max_digits=7, decimal_places=1)
    adrenals_combined = models.DecimalField(max_digits=7, decimal_places=1)
    pancreas = models.DecimalField(max_digits=7, decimal_places=1)
    
class ss_linga(models.Model):
    body_weight = models.CharField(max_length=20)
    gestational_age = models.IntegerField()
    crown_rump = models.DecimalField(max_digits=7, decimal_places=1)
    crown_heel = models.DecimalField(max_digits=7, decimal_places=1)
    toe_heel = models.DecimalField(max_digits=7, decimal_places=1)
    brain = models.DecimalField(max_digits=7, decimal_places=1)
    thymus = models.DecimalField(max_digits=7, decimal_places=1)
    heart = models.DecimalField(max_digits=7, decimal_places=1)
    lungs_combined = models.DecimalField(max_digits=7, decimal_places=1)
    spleen = models.DecimalField(max_digits=7, decimal_places=1)
    liver = models.DecimalField(max_digits=7, decimal_places=1)
    kidneys_combined = models.DecimalField(max_digits=7, decimal_places=1)
    adrenals_combined = models.DecimalField(max_digits=7, decimal_places=1)
    pancreas = models.DecimalField(max_digits=7, decimal_places=1)
    
class ss_lingarg(models.Model):
    body_weight = models.CharField(max_length=20)
    gestational_age = models.IntegerField()
    crown_rump = models.DecimalField(max_digits=7, decimal_places=1)
    crown_heel = models.DecimalField(max_digits=7, decimal_places=1)
    toe_heel = models.DecimalField(max_digits=7, decimal_places=1)
    brain = models.DecimalField(max_digits=7, decimal_places=1)
    thymus = models.DecimalField(max_digits=7, decimal_places=1)
    heart = models.DecimalField(max_digits=7, decimal_places=1)
    lungs_combined = models.DecimalField(max_digits=7, decimal_places=1)
    spleen = models.DecimalField(max_digits=7, decimal_places=1)
    liver = models.DecimalField(max_digits=7, decimal_places=1)
    kidneys_combined = models.DecimalField(max_digits=7, decimal_places=1)
    adrenals_combined = models.DecimalField(max_digits=7, decimal_places=1)
    pancreas = models.DecimalField(max_digits=7, decimal_places=1)
    
class ss_sbga(models.Model):
    body_weight = models.CharField(max_length=20)
    gestational_age = models.IntegerField()
    crown_rump = models.DecimalField(max_digits=7, decimal_places=1)
    crown_heel = models.DecimalField(max_digits=7, decimal_places=1)
    toe_heel = models.DecimalField(max_digits=7, decimal_places=1)
    brain = models.DecimalField(max_digits=7, decimal_places=1)
    thymus = models.DecimalField(max_digits=7, decimal_places=1)
    heart = models.DecimalField(max_digits=7, decimal_places=1)
    lungs_combined = models.DecimalField(max_digits=7, decimal_places=1)
    spleen = models.DecimalField(max_digits=7, decimal_places=1)
    liver = models.DecimalField(max_digits=7, decimal_places=1)
    kidneys_combined = models.DecimalField(max_digits=7, decimal_places=1)
    adrenals_combined = models.DecimalField(max_digits=7, decimal_places=1)
    pancreas = models.DecimalField(max_digits=7, decimal_places=1)
    
class ss_sbgargs(models.Model):
    body_weight = models.CharField(max_length=20)
    gestational_age = models.IntegerField()
    crown_rump = models.DecimalField(max_digits=7, decimal_places=1)
    crown_heel = models.DecimalField(max_digits=7, decimal_places=1)
    toe_heel = models.DecimalField(max_digits=7, decimal_places=1)
    brain = models.DecimalField(max_digits=7, decimal_places=1)
    thymus = models.DecimalField(max_digits=7, decimal_places=1)
    heart = models.DecimalField(max_digits=7, decimal_places=1)
    lungs_combined = models.DecimalField(max_digits=7, decimal_places=1)
    spleen = models.DecimalField(max_digits=7, decimal_places=1)
    liver = models.DecimalField(max_digits=7, decimal_places=1)
    kidneys_combined = models.DecimalField(max_digits=7, decimal_places=1)
    adrenals_combined = models.DecimalField(max_digits=7, decimal_places=1)
    pancreas = models.DecimalField(max_digits=7, decimal_places=1)
    
class stinbw(models.Model):
    body_weight = models.CharField(max_length=20)
    l_weight = models.IntegerField()
    h_weight = models.IntegerField()
    gestational_age = models.IntegerField()
    crown_rump = models.DecimalField(max_digits=7, decimal_places=1)
    crown_heel = models.DecimalField(max_digits=7, decimal_places=1)
    toe_heel = models.DecimalField(max_digits=7, decimal_places=1)
    brain = models.DecimalField(max_digits=7, decimal_places=1)
    thymus = models.DecimalField(max_digits=7, decimal_places=1)
    heart = models.DecimalField(max_digits=7, decimal_places=1)
    lungs_combined = models.DecimalField(max_digits=7, decimal_places=1)
    spleen = models.DecimalField(max_digits=7, decimal_places=1)
    liver = models.DecimalField(max_digits=7, decimal_places=1)
    kidneys_combined = models.DecimalField(max_digits=7, decimal_places=1)
    adrenals_combined = models.DecimalField(max_digits=7, decimal_places=1)
    pancreas = models.DecimalField(max_digits=7, decimal_places=1)
    
class stinbwrg(models.Model):
    body_weight = models.CharField(max_length=20)
    l_weight = models.IntegerField()
    h_weight = models.IntegerField()
    gestational_age = models.IntegerField()
    crown_rump = models.DecimalField(max_digits=7, decimal_places=1)
    crown_heel = models.DecimalField(max_digits=7, decimal_places=1)
    toe_heel = models.DecimalField(max_digits=7, decimal_places=1)
    brain = models.DecimalField(max_digits=7, decimal_places=1)
    thymus = models.DecimalField(max_digits=7, decimal_places=1)
    heart = models.DecimalField(max_digits=7, decimal_places=1)
    lungs_combined = models.DecimalField(max_digits=7, decimal_places=1)
    spleen = models.DecimalField(max_digits=7, decimal_places=1)
    liver = models.DecimalField(max_digits=7, decimal_places=1)
    kidneys_combined = models.DecimalField(max_digits=7, decimal_places=1)
    adrenals_combined = models.DecimalField(max_digits=7, decimal_places=1)
    pancreas = models.DecimalField(max_digits=7, decimal_places=1)