# Generated by Django 3.1.2 on 2020-10-04 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boyd3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=20)),
                ('low_age', models.DecimalField(decimal_places=2, max_digits=10)),
                ('high_age', models.DecimalField(decimal_places=2, max_digits=10)),
                ('testes_no', models.IntegerField(default=0)),
                ('testes_wgt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('t_e_no', models.IntegerField(default=0)),
                ('t_e_wgt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sem_ves_no', models.IntegerField(default=0)),
                ('sem_ves_wgt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pgl_no', models.IntegerField(default=0)),
                ('pgl_wgt', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
